services:
  kali-linux:
    container_name: kali-linux
    image: lscr.io/linuxserver/kali-linux:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      CUSTOM_USER: ${KALI_USER:-admin}
      PASSWORD: ${KALI_PASSWORD}
      CUSTOM_RES: ${CUSTOM_RES:-1920x1080}
    volumes:
      - kali_config:/config
    shm_size: "1gb"

# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy